[build]
  command = "mix deps.get && mix assets.deploy && mix release"
  publish = "priv/static"
  functions = "netlify/functions"

[build.environment]
  MIX_ENV = "prod"
  PHX_SERVER = "true"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/phoenix-server"
  status = 200

[[redirects]]
  from = "/webhook/*"
  to = "/.netlify/functions/phoenix-server"
  status = 200

[[redirects]]
  from = "/hubspot/*"
  to = "/.netlify/functions/phoenix-server"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/phoenix-server"
  status = 200

[[redirects]]
  from = "/live/*"
  to = "/.netlify/functions/phoenix-server"
  status = 200

[[redirects]]
  from = "/socket/*"
  to = "/.netlify/functions/phoenix-server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
