[phases.setup]
nixPkgs = ["elixir", "erlang", "nodejs", "python3", "postgresql"]

[phases.install]
cmds = [
  "mix local.hex --force",
  "mix local.rebar --force",
  "mix deps.get",
  "npm install --prefix assets",
  "pip install -r requirements.txt",
  "mix assets.deploy"
]

[phases.build]
cmds = ["mix compile"]

[start]
cmd = "python embedding_server.py & mix phx.server" 