[phases.setup]
nixPkgs = ["elixir", "erlang", "nodejs", "python3", "postgresql"]

[phases.install]
cmds = [
  "mix local.hex --force",
  "mix local.rebar --force",
  "mix deps.get",
  "npm install --prefix assets"
]

[phases.build]
cmds = [
  "cd assets && npm run build || true",
  "mix compile"
]

[start]
cmd = "pip install -r requirements.txt && python embedding_server.py & mix phx.server" 