[build]
builder = "nixpacks"

[deploy]
startCommand = "python embedding_server.py & mix phx.server"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
MIX_ENV = "prod" 