services:
  - type: web
    name: advisor-ai
    env: elixir
    plan: free
    buildCommand: mix deps.get && mix assets.deploy && mix release
    startCommand: _build/prod/rel/advisor_ai/bin/advisor_ai start
    envVars:
      - key: MIX_ENV
        value: prod
      - key: PHX_SERVER
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: advisor-ai-db
          property: connectionString
      - key: PHX_HOST
        value: advisor-ai.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: HUBSPOT_CLIENT_ID
        sync: false
      - key: HUBSPOT_CLIENT_SECRET
        sync: false
      - key: HUBSPOT_REDIRECT_URI
        value: https://advisor-ai.onrender.com/hubspot/oauth/callback
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: WEBHOOK_URL
        value: https://advisor-ai.onrender.com/webhook/gmail

databases:
  - name: advisor-ai-db
    plan: free
    databaseName: advisor_ai
    user: advisor_ai
